### ISSUE TITLE
USE=bindist 

### ISSUE THREAD

**Issue by aTosser** [sakaki-/gentoo-on-rpi3-64bit#46]
Is there a reason why the binhost packages are built with USE=bindist or is it just because that is part of the default layout? I find that I am unable to install any packages that rely on openSSL because they require EC and that is removed with the bindist USE. If there is no reason for it can you update the binhost to USE=-bindist and update the make.conf you distribute to include this change?

**Comment by sakaki-** [comment]
Yes, the `bindist` flag means "[OK (in a legal, rather than technical sense) for binary distribution](https://forums.gentoo.org/viewtopic-t-1071564-highlight-bindist.html)". Gentoo has a somewhat less liberal view of the patent situation of EC etc. than other distros on this point unfortunately.

Closing as "wontfix" until / if the `bindist` flag meaning for openSSL gets changed (see [Gentoo bug # 531540](https://bugs.gentoo.org/531540)). You can always override the `bindist` flag for openSSL locally and rebuild locally if you choose (rather than relying on the binhost). Sorry ><
